dist: xenial
language: python
matrix:
    fast_finish: true
addons:
  apt: 
    packages:
      - libgnutls-dev
# For a list of available versions, run
#     aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
jobs:
  include:
    # 3.5.2 is interesting because it's the version in ubuntu 16.04, and due to python's
    # "provisional feature" rules there are significant differences between patch
    # versions for asyncio and typing.
    - python: 3.5.2
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
- python: pypy3.5-5.10.1
sudo: true
#command to install dependancies
install:
  - pip install -r requirements.txt
  - pip install coveralls
#Command to run scripts
script:
  - pytest
after_success:
  - coveralls

# command to install dependencies