language: python
sudo: "required"
dist: "xenial"
python: 
  -"3.5.2"
#command to install dependancies
install:
  - pip install -r requirements.txt
  - pip install coveralls
#Command to run scripts
script:
  - pytest
after_success:
  - coveralls
