dist: xenial
language: python
python:
    - 2.7
    - 3.5
    - 3.6

sudo: true
#command to install dependancies
install:
  - pip install -r requirements.txt
  - pip install coveralls
#Command to run scripts
script:
  - pytest
after_success:
  - coveralls

# command to install dependencies