dist: xenial
language: python
python:
    - 3.5
    - 3.6
    - 3.7
sudo: true
addons:
  postgresql: "9.5"
services:
  - postgresql
#command to install dependancies
install:
  - 'pip install -r requirements.txt'
  - 'pip install coveralls'
  - 'pip install pytest-cov'
  - 'pip install pipenv'
  - 'pip install coverage==4.4'
  - 'pip install codeclimate-test-reporter'
  # - 'pipenv sync'

before_script:
- psql -c 'create database questionhubtest;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
  - py.test --cov-report= --cov=tests/
  - coverage
  # - bundle exec rspec
  - codeclimate-test-reporter --file .coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
  # - codeclimate-test-reporter

# command to install dependencies