dist: xenial
language: python
python:
    - 3.5
    - 3.6
    - 3.7
sudo: true
addons:
  postgresql: "9.5"
services:
  - postgresql
#command to install dependancies
install:
  - 'pip install -r requirements.txt'
  - 'pip install coveralls'
  - 'pip install pytest-cov'
  - 'pip install pipenv'
  - 'pip install coverage'
  # - 'pipenv sync'

before_script:
- psql -c 'create database questionhubtest;' -U postgres
script:
  - py.test --cov=tests/
after_success:
  - coveralls

# command to install dependencies